In [2]:
import pandas as pd

In [3]:
file="Resources/unicef_africa_data.csv"

In [4]:
df=pd.read_csv(file)

In [47]:
df.head(5)

Geographic area              Indicator     Sex TIME_PERIOD  \
0         Algeria  Infant mortality rate  Female        1954   
1         Algeria  Infant mortality rate  Female        1955   
2         Algeria  Infant mortality rate  Female        1956   
3         Algeria  Infant mortality rate  Female        1957   
4         Algeria  Infant mortality rate  Female        1958   

          OBS_VALUE Unit multiplier              Unit of measure  \
0  140.478076964498             NaN  Deaths per 1000 live births   
1  140.204233486295             NaN  Deaths per 1000 live births   
2  140.120652645222             NaN  Deaths per 1000 live births   
3  139.949659665834             NaN  Deaths per 1000 live births   
4  139.776068575784             NaN  Deaths per 1000 live births   

  Observation Status Observation confidentaility       LOWER_BOUND  ...  \
0       Normal value                         NaN  111.977302130197  ...   
1       Normal value                         NaN  115.228306909014  ...   
2       Normal value                         NaN  118.212999294601  ...   
3       Normal value                         NaN   120.41395512406  ...   
4       Normal value                         NaN  122.361114920809  ...   

  OBS_FOOTNOTE  SERIES_FOOTNOTE DATA_SOURCE SOURCE_LINK CUSTODIAN  \
0          NaN              NaN         NaN         NaN       NaN   
1          NaN              NaN         NaN         NaN       NaN   
2          NaN              NaN         NaN         NaN       NaN   
3          NaN              NaN         NaN         NaN       NaN   
4          NaN              NaN         NaN         NaN       NaN   

  Time period activity related to when the data are collected REF_PERIOD  \
0                                                NaN                 NaN   
1                                                NaN                 NaN   
2                                                NaN                 NaN   
3                                                NaN                 NaN   
4                                                NaN                 NaN   

  COVERAGE_TIME Current age continent  
0           NaN       Total    Africa  
1           NaN       Total    Africa  
2           NaN       Total    Africa  
3           NaN       Total    Africa  
4           NaN       Total    Africa  

[5 rows x 22 columns]

In [6]:
df["Indicator"].unique()

array(['Infant mortality rate', 'Under-five mortality rate',
       'Child mortality rate (aged 1-4 years)', 'Infant deaths',
       'Under-five deaths', 'Child deaths (aged 1-4 years)',
       'Youth literacy rate for 15-24 years', 'Mean BMI-for-age',
       'BMI-for-age <-1 SD', 'BMI-for-age <-2 SD', 'BMI-for-age <-3 SD',
       'BMI-for-age >+1 SD', 'BMI-for-age >+2 SD', 'BMI-for-age >+3 SD',
       'BMI-for-age (Standard Deviation)',
       'Height-for-age <-2SD & Weight-for-height <-2SD',
       'Height-for-age <-2SD & Weight-for-height >+2SD',
       'Height-for-age <-3SD & Weight-for-height <-2SD',
       'Height-for-age <-3SD & Weight-for-height >+2SD',
       'Mean Height-for-age', 'Height-for-age <-1 SD',
       'Height-for-age <-2 SD (stunting)',
       'Height-for-age <-3 SD (Severe Stunting)', 'Height-for-age >+1 SD',
       'Height-for-age >+2 SD', 'Height-for-age >+3 SD',
       'Height-for-age (Standard Deviation)', 'Weight-for-age (Mean)',
       'Weight-for-age <-1 SD

### PMI indicators as listed on PMI Website
* All-cause under-five mortality rate* 

* Proportion of households with at least one ITN

* Proportion of children under five years old who slept under an ITN the previous night 

* Proportion of pregnant women who slept under an ITN the previous night

* Proportion of women who received two or more doses of intermittent preventive treatment for pregnant women (IPTp)
during their last pregnancy in the last 2 years 

### PMI indicators as listed in Unicef dataset (This dataset)
* Under-five mortality rate
* Percentage of households with at least one insecticide-treated mosquito net (ITN)
* ITN use by children - percentage of children (under age 5) who slept under an insecticide-treated mosquito net the night prior to the survey
* Pregnant women sleeping under ITN - percentage of pregnant women (aged 15-49 years) who slept under an insecticide-treated net the previous night
* 'IPTp for pregnant women - percentage of women (aged 15-49 years) who received three or more doses of intermittent preventive treatment during antenatal care visits during their last pregnancy.  (*This indicator is a phrased a little differently than indicator on PMI website as shown above -- 2 years phrase*)


In [7]:
malaria_df=df.loc[(df["Indicator"]=='Under-five mortality rate')|
                  (df["Indicator"]=='Percentage of households with at least one insecticide-treated mosquito net (ITN)')|
                  (df["Indicator"]=='ITN use by children - percentage of children (under age 5) who slept under an insecticide-treated mosquito net the night prior to the survey')|
                  (df["Indicator"]=='Pregnant women sleeping under ITN - percentage of pregnant women (aged 15-49 years) who slept under an insecticide-treated net the previous night')|
                  (df["Indicator"]=='PTp for pregnant women - percentage of women (aged 15-49 years) who received three or more doses of intermittent preventive treatment during antenatal care visits during their last pregnancy'),:] 

In [8]:
malaria_df

Geographic area                                          Indicator  \
66             Algeria                          Under-five mortality rate   
67             Algeria                          Under-five mortality rate   
68             Algeria                          Under-five mortality rate   
69             Algeria                          Under-five mortality rate   
70             Algeria                          Under-five mortality rate   
...                ...                                                ...   
178800        Zimbabwe  Percentage of households with at least one ins...   
178801        Zimbabwe  Percentage of households with at least one ins...   
178802        Zimbabwe  Percentage of households with at least one ins...   
178803        Zimbabwe  Percentage of households with at least one ins...   
178804        Zimbabwe  Percentage of households with at least one ins...   

           Sex TIME_PERIOD         OBS_VALUE Unit multiplier  \
66      Female        1954  239.290372677429             NaN   
67      Female        1955  238.452606077294             NaN   
68      Female        1956  238.280275049517             NaN   
69      Female        1957  237.927117039717             NaN   
70      Female        1958  237.570487874157             NaN   
...        ...         ...               ...             ...   
178800   Total        2009              27.4           Units   
178801   Total        2011              28.8           Units   
178802   Total        2014              42.2           Units   
178803   Total        2015              47.9           Units   
178804   Total        2019              36.8           Units   

                    Unit of measure Observation Status  \
66      Deaths per 1000 live births       Normal value   
67      Deaths per 1000 live births       Normal value   
68      Deaths per 1000 live births       Normal value   
69      Deaths per 1000 live births       Normal value   
70      Deaths per 1000 live births       Normal value   
...                             ...                ...   
178800                            %           Reported   
178801                            %           Reported   
178802                            %           Reported   
178803                            %           Reported   
178804                            %           Reported   

       Observation confidentaility       LOWER_BOUND  ... OBS_FOOTNOTE  \
66                             NaN  178.079240969729  ...          NaN   
67                             NaN   185.23752007373  ...          NaN   
68                             NaN  191.747176067565  ...          NaN   
69                             NaN  196.584571541898  ...          NaN   
70                             NaN   200.53550190015  ...          NaN   
...                            ...               ...  ...          ...   
178800                        Free               NaN  ...          NaN   
178801                        Free               NaN  ...          NaN   
178802                        Free               NaN  ...          NaN   
178803                        Free               NaN  ...          NaN   
178804                        Free               NaN  ...          NaN   

        SERIES_FOOTNOTE                              DATA_SOURCE SOURCE_LINK  \
66                  NaN                                      NaN         NaN   
67                  NaN                                      NaN         NaN   
68                  NaN                                      NaN         NaN   
69                  NaN                                      NaN         NaN   
70                  NaN                                      NaN         NaN   
...                 ...                                      ...         ...   
178800              NaN   Multiple Indicator Cluster Survey 2009         NaN   
178801              NaN  Demographic and Health Survey 2010-2011         NaN   
178802 

In [9]:
malaria_df['TIME_PERIOD'].unique()

array(['1954', '1955', '1956', '1957', '1958', '1959', '1960', '1961',
       '1962', '1963', '1964', '1965', '1966', '1967', '1968', '1969',
       '1970', '1971', '1972', '1973', '1974', '1975', '1976', '1977',
       '1978', '1979', '1980', '1981', '1982', '1983', '1984', '1985',
       '1986', '1987', '1988', '1989', '1990', '1991', '1992', '1993',
       '1994', '1995', '1996', '1997', '1998', '1999', '2000', '2001',
       '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009',
       '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017',
       '2018', '2019', '1950', '1951', '1952', '1953', '2012-06', '2020',
       '2010-06', '2015-06', '2000-06', '2017-06', '2018-06'],
      dtype=object)

In [10]:
#Selecting rows with years >=2000
malaria_2000_df= malaria_df.loc[malaria_df["TIME_PERIOD"].str.contains("20"),:]

In [11]:
malaria_2000_df

Geographic area                                          Indicator  \
112            Algeria                          Under-five mortality rate   
113            Algeria                          Under-five mortality rate   
114            Algeria                          Under-five mortality rate   
115            Algeria                          Under-five mortality rate   
116            Algeria                          Under-five mortality rate   
...                ...                                                ...   
178800        Zimbabwe  Percentage of households with at least one ins...   
178801        Zimbabwe  Percentage of households with at least one ins...   
178802        Zimbabwe  Percentage of households with at least one ins...   
178803        Zimbabwe  Percentage of households with at least one ins...   
178804        Zimbabwe  Percentage of households with at least one ins...   

           Sex TIME_PERIOD         OBS_VALUE Unit multiplier  \
112     Female        2000  36.6523430868736             NaN   
113     Female        2001  35.9718315660602             NaN   
114     Female        2002  34.7811218489329             NaN   
115     Female        2003  33.9773107456524             NaN   
116     Female        2004  32.8598778682843             NaN   
...        ...         ...               ...             ...   
178800   Total        2009              27.4           Units   
178801   Total        2011              28.8           Units   
178802   Total        2014              42.2           Units   
178803   Total        2015              47.9           Units   
178804   Total        2019              36.8           Units   

                    Unit of measure Observation Status  \
112     Deaths per 1000 live births       Normal value   
113     Deaths per 1000 live births       Normal value   
114     Deaths per 1000 live births       Normal value   
115     Deaths per 1000 live births       Normal value   
116     Deaths per 1000 live births       Normal value   
...                             ...                ...   
178800                            %           Reported   
178801                            %           Reported   
178802                            %           Reported   
178803                            %           Reported   
178804                            %           Reported   

       Observation confidentaility       LOWER_BOUND  ... OBS_FOOTNOTE  \
112                            NaN   35.796905485145  ...          NaN   
113                            NaN  35.1942594790876  ...          NaN   
114                            NaN  34.0560914913844  ...          NaN   
115                            NaN  33.2817987041951  ...          NaN   
116                            NaN  32.2063157098561  ...          NaN   
...                            ...               ...  ...          ...   
178800                        Free               NaN  ...          NaN   
178801                        Free               NaN  ...          NaN   
178802                        Free               NaN  ...          NaN   
178803                        Free               NaN  ...          NaN   
178804                        Free               NaN  ...          NaN   

        SERIES_FOOTNOTE                              DATA_SOURCE SOURCE_LINK  \
112                 NaN                                      NaN         NaN   
113                 NaN                                      NaN         NaN   
114                 NaN                                      NaN         NaN   
115                 NaN                                      NaN         NaN   
116                 NaN                                      NaN         NaN   
...                 ...                                      ...         ...   
178800              NaN   Multiple Indicator Cluster Survey 2009         NaN   
178801              NaN  Demographic and Health Survey 2010-2011         NaN   
178802 

### Exploring nature of the data

In [21]:
#malaria_2000_df.describe

In [19]:
malaria_2000_df.columns

Index(['Geographic area', 'Indicator', 'Sex', 'TIME_PERIOD', 'OBS_VALUE',
       'Unit multiplier', 'Unit of measure', 'Observation Status',
       'Observation confidentaility', 'LOWER_BOUND', 'UPPER_BOUND',
       'WGTD_SAMPL_SIZE', 'OBS_FOOTNOTE', 'SERIES_FOOTNOTE', 'DATA_SOURCE',
       'SOURCE_LINK', 'CUSTODIAN',
       'Time period activity related to when the data are collected',
       'REF_PERIOD', 'COVERAGE_TIME', 'Current age', 'continent'],
      dtype='object')

In [23]:
malaria_2000_df["Geographic area"].unique()

array(['Algeria', 'Angola', 'Benin', 'Botswana', 'Burkina Faso',
       'Burundi', 'Cameroon', 'Central African Republic', 'Chad',
       'Democratic Republic of the Congo', 'Djibouti', 'Egypt',
       'Equatorial Guinea', 'Eritrea', 'Ethiopia', 'Gabon', 'Gambia',
       'Ghana', 'Guinea', 'Kenya', 'Lesotho', 'Liberia', 'Libya',
       'Madagascar', 'Malawi', 'Mali', 'Mauritania', 'Morocco',
       'Mozambique', 'Namibia', 'Niger', 'Nigeria', 'Rwanda', 'Senegal',
       'Sierra Leone', 'Somalia', 'South Africa', 'South Sudan', 'Sudan',
       'Togo', 'Tunisia', 'Uganda', 'Zambia', 'Zimbabwe'], dtype=object)

In [24]:
malaria_2000_df["Indicator"].unique()

array(['Under-five mortality rate',
       'ITN use by children - percentage of children (under age 5) who slept under an insecticide-treated mosquito net the night prior to the survey',
       'Pregnant women sleeping under ITN - percentage of pregnant women (aged 15-49 years) who slept under an insecticide-treated net the previous night',
       'Percentage of households with at least one insecticide-treated mosquito net (ITN)'],
      dtype=object)

In [25]:
malaria_2000_df["Sex"].unique()

array(['Female', 'Male', 'Total'], dtype=object)

In [26]:
malaria_2000_df["TIME_PERIOD"].unique()

array(['2000', '2001', '2002', '2003', '2004', '2005', '2006', '2007',
       '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015',
       '2016', '2017', '2018', '2019', '2012-06', '2020', '2010-06',
       '2015-06', '2000-06', '2017-06', '2018-06'], dtype=object)

In [27]:
malaria_2000_df["OBS_VALUE"].unique()

array(['36.6523430868736', '35.9718315660602', '34.7811218489329', ...,
       '14.9', '28.8', '36.8'], dtype=object)

In [28]:
malaria_2000_df["Unit multiplier"].unique()

array([nan, 'Units'], dtype=object)

In [29]:
malaria_2000_df["Unit of measure"].unique()

array(['Deaths per 1000 live births', '%'], dtype=object)

In [30]:
malaria_2000_df["Observation Status"].unique()

array(['Normal value', 'Reported'], dtype=object)

In [31]:
malaria_2000_df["Observation confidentaility"].unique()

array([nan, 'Free'], dtype=object)

In [32]:
malaria_2000_df["LOWER_BOUND"].unique()

array(['35.796905485145', '35.1942594790876', '34.0560914913844', ...,
       '48.083919820899', '44.136918069885', '41.0768015098153'],
      dtype=object)

In [33]:
malaria_2000_df["UPPER_BOUND"].unique()

array(['37.5341623904933', '36.7485873162453', '35.5044010262278', ...,
       '69.9875702827525', '70.0768867331187', '71.7098923757762'],
      dtype=object)

In [34]:
malaria_2000_df["WGTD_SAMPL_SIZE"].unique() #Drop this column, it is empty 1

array([nan])

In [35]:
malaria_2000_df["OBS_FOOTNOTE"].unique()

array([nan,
       'The most recent national official estimates of neonatal, infant and under-five mortality rates in Zambia are from the 2018 Zambia Demographic and Health Survey (2018 ZDHS) with a rate of 27, 42 and 61 deaths per 1,000 live births, respectively, in the 5-year period before the survey.'],
      dtype=object)

In [36]:
malaria_2000_df["SERIES_FOOTNOTE"].unique() #Drop this column, it is empty 2

array([nan], dtype=object)

In [37]:
malaria_2000_df["DATA_SOURCE"].unique()

array([nan, 'Other NS 2006-2007', 'Malaria Indicator Survey 2011',
       'Demographic and Health Survey 2015-2016',
       'Malaria Indicator Survey 2006-2007',
       'Demographic and Health Survey 2001',
       'Demographic and Health Survey 2006',
       'Demographic and Health Survey 2011-2012',
       'Demographic and Health Survey 2017-2018',
       'Multiple Indicator Cluster Survey 2014',
       'Malaria Indicator Survey 2012',
       'Demographic and Health Survey 2003',
       'Multiple Indicator Cluster Survey 2006',
       'Demographic and Health Survey 2010',
       'Malaria Indicator Survey 2014',
       'Malaria Indicator Survey 2017-2018',
       'Multiple Indicator Cluster Survey 2000',
       'Multiple Indicator Cluster Survey 2005',
       'Enquete ménages pour le suivi... 2012',
       'Demographic and Health Survey 2016',
       'Demographic and Health Survey 2004',
       'Demographic and Health Survey 2011',
       'Demographic and Health Survey Key Indicators R

In [38]:
malaria_2000_df["SOURCE_LINK"].unique() #Drop this column, it is empty 3

array([nan], dtype=object)

In [39]:
malaria_2000_df["CUSTODIAN"].unique() #Drop this column it is empty  4

array([nan], dtype=object)

In [40]:
malaria_2000_df["Time period activity related to when the data are collected"].unique() #Drop this column it is empty 5

array([nan], dtype=object)

In [41]:
malaria_2000_df["REF_PERIOD"].unique() #Drop this column it is empty 6

array([nan], dtype=object)

In [42]:
malaria_2000_df["COVERAGE_TIME"].unique() #Drop this column it is empty 7

array([nan], dtype=object)

In [43]:
malaria_2000_df["Current age"].unique() 

array(['Total', 'Under 5 years old', '15 to 49 years old'], dtype=object)

In [44]:
malaria_2000_df["continent"].unique()

array(['Africa'], dtype=object)

In [46]:
#Columns removed because they are empty:--
#WGTD_SAMPL_SIZE,SERIES_FOOTNOTE, SOURCE_LINK, CUSTODIAN, Time period activity related to when the data are collected,
#REF_PERIOD, COVERAGE_TIME

#Removed continent identifier because they are all African countries

#Columns to keep based on data explration above
malaria_africa_2000=malaria_2000_df[['Geographic area', 'Indicator', 'Sex', 'TIME_PERIOD', 'OBS_VALUE','Unit multiplier', 
    'Unit of measure', 'Observation Status','Observation confidentaility', 'LOWER_BOUND','UPPER_BOUND', 'OBS_FOOTNOTE',
    'DATA_SOURCE','Current age']]

malaria_africa_2000.head(5)

Geographic area                  Indicator     Sex TIME_PERIOD  \
112         Algeria  Under-five mortality rate  Female        2000   
113         Algeria  Under-five mortality rate  Female        2001   
114         Algeria  Under-five mortality rate  Female        2002   
115         Algeria  Under-five mortality rate  Female        2003   
116         Algeria  Under-five mortality rate  Female        2004   

            OBS_VALUE Unit multiplier              Unit of measure  \
112  36.6523430868736             NaN  Deaths per 1000 live births   
113  35.9718315660602             NaN  Deaths per 1000 live births   
114  34.7811218489329             NaN  Deaths per 1000 live births   
115  33.9773107456524             NaN  Deaths per 1000 live births   
116  32.8598778682843             NaN  Deaths per 1000 live births   

    Observation Status Observation confidentaility       LOWER_BOUND  \
112       Normal value                         NaN   35.796905485145   
113       Normal value                         NaN  35.1942594790876   
114       Normal value                         NaN  34.0560914913844   
115       Normal value                         NaN  33.2817987041951   
116       Normal value                         NaN  32.2063157098561   

          UPPER_BOUND OBS_FOOTNOTE DATA_SOURCE Current age  
112  37.5341623904933          NaN         NaN       Total  
113  36.7485873162453          NaN         NaN       Total  
114  35.5044010262278          NaN         NaN       Total  
115  34.6849462793851          NaN         NaN       Total  
116  33.5270875453734          NaN         NaN       Total

### Differentiating PMI  countries and Non-PMI countries

In [54]:
african_countries=["Algeria","Angola","Benin","Botswana","Burkina Faso","Burundi","Cameroon","Central African Republic",
                   "Chad","Democratic Republic of the Congo","Republic of the Congo","Ivory Coast","Djibouti","Egypt",
                   "Equatorial Guinea","Eritrea","Swaziland","Ethiopia","Gabon","Gambia","Ghana","Guinea","Guinea Bissau",
                   "Kenya","Lesotho","Liberia","Libya","Madagascar","Malawi","Mali", "Mauritania","Morocco","Mozambique",
                   "Namibia","Niger","Nigeria","Rwanda","Senegal","Sierra Leone","Somalia","South Africa",
                    "South Sudan","Sudan","Tanzania","Togo","Tunisia","Uganda","Zambia","Zimbabwe"]

In [55]:
#24 focus countries in Africa
PMI_countries=["Angola","Benin","Burkina Faso","Cameroon","Côte d'Ivoire","Democratic Republic of the Congo","Ethiopia",
                   "Ghana","Guinea","Kenya","Liberia","Madagascar","Malawi","Mali","Niger","Mozambique","Nigeria","Rwanda",
               "Senegal","Sierra Leone","Tanzania","Uganda","Zambia","Zimbabwe"]

In [59]:
import numpy as np
non_PMI_countries = np.setdiff1d(african_countries,PMI_countries)
non_PMI_countries

array(['Algeria', 'Botswana', 'Burundi', 'Central African Republic',
       'Chad', 'Djibouti', 'Egypt', 'Equatorial Guinea', 'Eritrea',
       'Gabon', 'Gambia', 'Guinea Bissau', 'Ivory Coast', 'Lesotho',
       'Libya', 'Mauritania', 'Morocco', 'Namibia',
       'Republic of the Congo', 'Somalia', 'South Africa', 'South Sudan',
       'Sudan', 'Swaziland', 'Togo', 'Tunisia'], dtype='<U32')

In [62]:
# Creating DataFrame from PMI countries
PMI_df=pd.DataFrame(PMI_countries, columns=["Geographic Area"])
PMI_df["Category"]="PMI country"
PMI_df

Geographic Area     Category
0                             Angola  PMI country
1                              Benin  PMI country
2                       Burkina Faso  PMI country
3                           Cameroon  PMI country
4                      Côte d'Ivoire  PMI country
5   Democratic Republic of the Congo  PMI country
6                           Ethiopia  PMI country
7                              Ghana  PMI country
8                             Guinea  PMI country
9                              Kenya  PMI country
10                           Liberia  PMI country
11                        Madagascar  PMI country
12                            Malawi  PMI country
13                              Mali  PMI country
14                             Niger  PMI country
15                        Mozambique  PMI country
16                           Nigeria  PMI country
17                            Rwanda  PMI country
18                           Senegal  PMI country
19                      Sierra Leone  PMI country
20                          Tanzania  PMI country
21                            Uganda  PMI country
22                            Zambia  PMI country
23                          Zimbabwe  PMI country

In [64]:
# Creating DataFrame from non-PMI countries
non_PMI_df=pd.DataFrame(non_PMI_countries, columns=["Geographic Area"])
non_PMI_df["Category"]="non PMI country"
non_PMI_df

Geographic Area         Category
0                    Algeria  non PMI country
1                   Botswana  non PMI country
2                    Burundi  non PMI country
3   Central African Republic  non PMI country
4                       Chad  non PMI country
5                   Djibouti  non PMI country
6                      Egypt  non PMI country
7          Equatorial Guinea  non PMI country
8                    Eritrea  non PMI country
9                      Gabon  non PMI country
10                    Gambia  non PMI country
11             Guinea Bissau  non PMI country
12               Ivory Coast  non PMI country
13                   Lesotho  non PMI country
14                     Libya  non PMI country
15                Mauritania  non PMI country
16                   Morocco  non PMI country
17                   Namibia  non PMI country
18     Republic of the Congo  non PMI country
19                   Somalia  non PMI country
20              South Africa  non PMI country
21               South Sudan  non PMI country
22                     Sudan  non PMI country
23                 Swaziland  non PMI country
24                      Togo  non PMI country
25                   Tunisia  non PMI country

In [18]:
malaria_2000_df.to_csv('../US_Africa_Policy/Resources/malaria.csv',index=False)